### ISSUE TITLE
BombArena - Wrong team spawns

### ISSUE THREAD

**Issue by tara81** [BattlePluginsDev/BattleArena#19]
SND - 
When the bomb is moved , the teams get spawned on the opposite team spawns. This makes it hard to allow players to use class signs based on their team.

**Comment by clovisd** [comment]
Could you please reiterate what is not working. We're having trouble understanding the problem you're talking about.

Based on the title of the ticket, I'm guessing you mean teams aren't spawning where you wanted them to spawn?

**Comment by tara81** [comment]
yes the "red team" is the defenders of the base and the "blue team" is the attackers who can pick up the bomb.

When the bomb gets moved closer to the "red team's spawn point" the "blue team" spawns at the red teams spawn point and sometimes the red team spawns at the blue teams spawn point.  I made rooms for each teams spawn point so they could select classes based on their rank and team.

eg. - resource pack makes team red look like the rebellion, blue team looks like the empire.

When the blue team is spawning in the red teams spawn, they can only select a class with the armor that makes them look like the opposite team.  Not to mention its very confusing for the player to see enemey in their spawn location.

**Comment by tara81** [comment]
The teams spawn in opposite spawn points then defined, once the bomb moves,  in /snd alter sndarena1 1 , /snd alter sndarena2

**Comment by Europia79** [comment]
Are you "moving" the bomb BEFORE the game with ```/snd spawnbomb <arenaName>``` ? Or is the bomb being "moved" DURING the game ? (by a player picking it up and moving closer to the other spawn ? And/or dropping it ?)

**Comment by Europia79** [comment]
http://webchat.esper.net/?nick=&channels=battledev

Can you log in IRC and help me with this issue ?

**Comment by tara81** [comment]
The bomb is being moved during the game, by the empire team picking it up, then dying near the base

**Comment by Europia79** [comment]
http://wiki.battleplugins.org/BattleArena/Options#onDeath_Options

This was caused by onDeath: [randomRespawn]

Altho, I'm not sure if this is the intended behavior, or if it's an actual bug.

For [randomRespawn], should the location be chosen from ALL POSSIBLE locations (regardless of which team the location belongs to) ? Or should the location be chosen only from team spawn points ? 

I'm thinking, ideally, server owners/admins should be able to configure it either way: They should be able to choose the "randomRespawn" behavior that BattleArena uses.
