### ISSUE TITLE
[Suggestion] Less Spam in chat

### ISSUE THREAD

**Issue by Blackyvk** [BattlePluginsDev/BattleArena#34]
I Know plugins use the action bar now to announce things and not the chat, people likes to know who is fighting, joining queue or wins a match, but this also spams the chat.

Is there a way to change this and announce in the action bar (or somehwhere else) instead of the chat ?

http://www.spigotmc.org/resources/actionannouncer.1320/

**Comment by Zach443** [comment]
What messages seem spammy to you?

**Comment by Blackyvk** [comment]
well actually all of them could get spammy, imagine if i had 20 matchs in a row. Its announced the fight player1 vs player2 and then the player1 defeadted player2, imagine that in just 10 seconds in very short fights, if someone was chatting it will be gone. I had to remove all those annoucements and only leave the "joined the queue" so at least people know who is if someone looking for a fight.

maybe i ask too much but i think it could be nice to have that as an option, "broadcast in chat" "dont broadcast" "broadcast in action bar" or somewhere else.

**Comment by Zach443** [comment]
You can set the plugin to either not broadcast at all, broadcast to everyone (default), or just broadcast to people involved in the arena. 
http://wiki.battleplugins.org/BattleArena/ConfigAdvanced#default_Match_Options_.28these_can_be_overridden_by_each_match_type.29

**Comment by Blackyvk** [comment]
yeah but my idea was to let everyone know what happening in the arenas without spamming the chat, but thanks anyway. i'll leave it like this so it doesnt spam.

**Comment by Europia79** [comment]
> I Know plugins use the action bar now to announce things and not the chat, people likes to know who is fighting, joining queue or wins a match, but this also spams the chat.

> Is there a way to change this and announce in the action bar (or somehwhere else) instead of the chat ?

I think this is a good idea... because as you said in your example, you could potentially have a lot of BattleArena announcements all at once... And someone could miss an actual chat message because of it. It's too bad that Minecraft doesn't have multiple chat tabs like World of Warcraft (for example)... So that you could have one tab for private messages, one for logs + announcements, one for general chat, one for world chat, one for trade chat, etc.

But yeah, you're right... the next best thing would probably be using the action bar.
